###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  mariadb:
    image: 'mariadb:10.6'
    working_dir: /application
    volumes:
      - 'db-data:/var/lib/mysql'
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
    ports:
      - '6003:3306'

  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

#  mailer:
#    image: schickling/mailcatcher
#    ports: [1025, 1080]

volumes:
  db-data:
